package main

import (
	_ "embed"
)

// cg_prompt_reference.go — the full partyline reference, served as an MCP prompt.
//
// WHY A PROMPT AND NOT THE BRIEFING. cg_instructions.go already hands every session a short,
// state-aware briefing at `initialize`. That one is injected into the system prompt of EVERY
// session whether it is wanted or not, so it stays deliberately small and says only where THIS repo
// stands and what to do next. It is not the place to explain what partyline is; ten kilobytes of
// reference in every system prompt is a tax on every turn of every conversation.
//
// This is the other half: the whole document, pulled in ON DEMAND when a model (or a person driving
// one) actually wants to understand partyline. Nothing about it is state-aware and nothing about it
// needs the control plane — so it works with no thread bound, signed out, and offline. Understanding
// the product is not a setup step.
//
// SAME BYTES AS THE URL. The document is web/public/llms-full.txt — the file Next.js serves at
// https://partyline.sh/llms-full.txt — embedded at build time rather than copied. It is itself
// GENERATED by internal/surfacegen from the declarations in the source tree, and `make surface-check`
// fails CI if the checked-in file drifts from the generator. Embedding that exact file is what makes
// "the prompt and the URL can never disagree" a property of the build instead of a promise: there is
// one artifact, and both surfaces hand out its bytes.
//
//go:embed web/public/llms-full.txt
var partylineReferenceDoc string

// partylineReferencePromptName is the prompt's name — the slash command a wired client surfaces
// (e.g. /mcp__partyline-context-threads__partyline_reference in Claude Code).
const partylineReferencePromptName = "partyline_reference"

const partylineReferencePromptDesc = "Load the FULL partyline reference — what it is, the trust " +
	"model, every `ptln` command, the vocabularies and the API surface — into this conversation. " +
	"Use it before answering questions about partyline or configuring it; it is generated from the " +
	"source tree, so it describes the version you are running. Needs no thread and no account."
