package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"partyline.sh/partyline/internal/ptymux"
)

// These two bugs cost a real session: a compacted conversation rendered as "This session is being
// continued from a previous conversation…" — the same string every other compacted session shows —
// and the --resume snapshot was stale, so the tab came back on an OLDER session id under the same
// name. Nothing was lost, but it read as lost, which is worse than a crash: a crash is honest.

func TestBoilerplateIsNeverATitle(t *testing.T) {
	for _, s := range []string{
		"This session is being continued from a previous conversation that ran out of context. The summary below…",
		"this session is being CONTINUED from a previous conversation",
		"Caveat: The messages below were generated by the user while running local commands.",
		"<command-name>/exit</command-name>",
	} {
		if got := cleanTitle(s); got != "" {
			t.Errorf("harness boilerplate became a title:\n  in:  %.60s\n  out: %q", s, got)
		}
	}
	// The filter must not eat a real message that merely mentions a session.
	for _, s := range []string{
		"this session keeps dropping — can you look?",
		"continue from where we left off",
	} {
		if cleanTitle(s) == "" {
			t.Errorf("rejected a real user message: %q", s)
		}
	}
}

// The title should be the LAST thing you said. The first is stale in any long session and absent
// in a compacted one — which is exactly the session that is hardest to find.
func TestScanClaudePrefersTheLatestMessage(t *testing.T) {
	path := filepath.Join(t.TempDir(), "s.jsonl")
	writeJSONL(t, path, []string{
		`{"type":"user","cwd":"/Users/x/dev/app","message":{"content":"This session is being continued from a previous conversation that ran out of context."}}`,
		`{"type":"user","message":{"content":"read the memory files for this project"}}`,
		`{"type":"assistant","message":{"content":[{"type":"text","text":"done"}]}}`,
		`{"type":"user","message":{"content":"get it running on cloudrun then switch DNS"}}`,
		// Trailing noise the scan must look past: a tool result and a slash command are not titles.
		`{"type":"user","message":{"content":[{"type":"tool_result","content":"ok"}]}}`,
		`{"type":"user","message":{"content":"<local-command-stdout>See ya!</local-command-stdout>"}}`,
	})
	cwd, title := scanClaude(path)
	if cwd != "/Users/x/dev/app" {
		t.Errorf("cwd = %q", cwd)
	}
	if !strings.Contains(title, "cloudrun") {
		t.Fatalf("title = %q, want the most recent real message (…cloudrun…)", title)
	}
}

// A session whose only user turn is the compaction summary must still say SOMETHING findable
// rather than falling back to the boilerplate it was just filtered for.
func TestCompactedSessionNeverShowsTheSummary(t *testing.T) {
	path := filepath.Join(t.TempDir(), "s.jsonl")
	writeJSONL(t, path, []string{
		`{"type":"user","cwd":"/tmp","message":{"content":"This session is being continued from a previous conversation that ran out of context."}}`,
		`{"type":"assistant","message":{"content":[{"type":"text","text":"working"}]}}`,
	})
	if _, title := scanClaude(path); strings.Contains(strings.ToLower(title), "being continued") {
		t.Fatalf("compacted session still titled by its summary: %q", title)
	}
}

// The snapshot must track the live set WHILE the mux runs. If it only lands on a clean quit, any
// session opened since the last quit is missing, and --resume restores that tab under its saved
// name pointing at a stale session id.
func TestWorkspaceSigTracksTheSessionSet(t *testing.T) {
	a := []ptymux.Spec{{Key: "k1"}, {Key: "k2"}}
	if workspaceSig(a) != workspaceSig([]ptymux.Spec{{Key: "k2"}, {Key: "k1"}}) {
		t.Error("reordering tabs counted as a change — would rewrite the file on every repaint")
	}
	if workspaceSig(a) == workspaceSig([]ptymux.Spec{{Key: "k1"}, {Key: "k3"}}) {
		t.Error("a REPLACED session read as no change — this is the lost-session bug")
	}
	if workspaceSig(a) == workspaceSig([]ptymux.Spec{{Key: "k1"}}) {
		t.Error("a closed session read as no change")
	}
	// A label edit is not a workspace change; only membership is.
	if workspaceSig(a) != workspaceSig([]ptymux.Spec{{Key: "k1", Label: "renamed"}, {Key: "k2"}}) {
		t.Error("a relabel rewrote the workspace")
	}
}

// saveWorkspace must never let an empty set erase a good snapshot — quitting the bare launcher
// would otherwise destroy exactly the thing --resume exists to restore.
func TestEmptySetNeverErasesTheWorkspace(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	saveWorkspace([]ptymux.Spec{{Key: "k1", Label: "ACR BACKLOG", Argv: []string{"claude", "--resume", "k1"}}})
	saveWorkspace(nil)
	if got := loadWorkspace(); len(got) != 1 || got[0].Key != "k1" {
		t.Fatalf("workspace wiped by an empty save: %+v", got)
	}
}

func writeJSONL(t *testing.T, path string, lines []string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
}
