package main

import (
	"fmt"
	"net"
	"strings"
)

// server_install_caddy.go — the edge config `ptln server install` writes.
//
// It is GENERATED, not copied. deploy/stack/Caddyfile.prod hardcodes `partyline.sh,
// www.partyline.sh`, so shipping it to a self-hoster produces an edge that matches no request they
// will ever make. (That shipped: a real box answered every request with a bare redirect because no
// site block matched its name.)
//
// MOST SELF-HOSTED BOXES HAVE NO PUBLIC DOMAIN. A LAN address, a Tailscale name, a `.local`, or a
// bare hostname is the normal case, not the exception — and Let's Encrypt cannot issue for any of
// them, because it validates by dialling the name from the public internet. So the TLS mode is
// chosen from the name rather than assumed:
//
//	public FQDN      → ACME. A real certificate, no browser warning.
//	anything else    → `tls internal`. Caddy mints one from its own local CA: HTTPS works
//	                   immediately, offline, with a warning until the CA is trusted.
//	http:// site     → no TLS at all, for a private network that does not want it.

type tlsMode string

const (
	tlsAuto     tlsMode = "auto"     // decide from the name
	tlsACME     tlsMode = "acme"     // Let's Encrypt
	tlsInternal tlsMode = "internal" // Caddy's own CA
	tlsOff      tlsMode = "off"      // plain HTTP
)

// resolveTLSMode turns the operator's choice (or lack of one) into a concrete mode.
func resolveTLSMode(want tlsMode, site string) tlsMode {
	scheme, host, _ := strings.Cut(site, "://")
	if want != tlsAuto && want != "" {
		return want
	}
	if scheme == "http" {
		return tlsOff
	}
	if publiclyIssuable(host) {
		return tlsACME
	}
	return tlsInternal
}

// publiclyIssuable reports whether a public CA could plausibly issue for this name.
//
// It is deliberately conservative: when in doubt, say no. A wrong "yes" means Caddy spends the
// install retrying ACME against a name that will never validate, and the operator gets a box that
// serves nothing over TLS. A wrong "no" costs only a browser warning that `tls internal` was
// always going to produce anyway.
func publiclyIssuable(host string) bool {
	host = strings.TrimSuffix(strings.ToLower(strings.TrimSpace(host)), ".")
	if h, _, err := net.SplitHostPort(host); err == nil {
		host = h
	}
	if host == "" {
		return false
	}
	// A literal IP can never get a public certificate from Let's Encrypt.
	if net.ParseIP(strings.Trim(host, "[]")) != nil {
		return false
	}
	// A single label (`monolith`, `localhost`) is not a public name.
	if !strings.Contains(host, ".") {
		return false
	}
	// Reserved and private-use suffixes. RFC 6761/8375 plus the ones people actually use on a
	// LAN, and .ts.net, which is Tailscale's — it resolves, but only inside your tailnet.
	for _, suffix := range []string{
		".local", ".localhost", ".test", ".invalid", ".example",
		".internal", ".home", ".home.arpa", ".lan", ".intranet",
		".private", ".corp", ".domain", ".ts.net",
	} {
		if strings.HasSuffix(host, suffix) {
			return false
		}
	}
	return true
}

// stripHostPort removes a trailing :port, leaving IPv6 literals intact.
func stripHostPort(host string) string {
	if h, _, err := net.SplitHostPort(host); err == nil {
		return h
	}
	return host
}

// siteHasPort reports whether the operator put an explicit port in --site.
func siteHasPort(site string) bool {
	_, host, _ := strings.Cut(site, "://")
	host = strings.TrimRight(host, "/")
	_, _, err := net.SplitHostPort(host)
	return err == nil
}

// tunnelFronted reports the tunnel shape: a public https:// site with our own TLS off. That is
// what Tailscale Serve and a Cloudflare Tunnel look like from here — a real certificate at the
// tunnel, plain HTTP into the stack.
func tunnelFronted(cfg installConfig) bool {
	scheme, _, _ := strings.Cut(cfg.site, "://")
	return scheme == "https" && resolveTLSMode(cfg.tls, cfg.site) == tlsOff
}

// isIPHost reports whether the site address is a bare IP literal rather than a name.
func isIPHost(host string) bool {
	return net.ParseIP(strings.Trim(host, "[]")) != nil
}

// caddyfileFor renders the edge config for this install.
func caddyfileFor(cfg installConfig) string {
	mode := resolveTLSMode(cfg.tls, cfg.site)
	_, host, _ := strings.Cut(cfg.site, "://")
	host = strings.TrimRight(host, "/")
	// Strip any port from the SITE ADDRESS. A Caddy site address with a port means "listen on
	// this port", which is the listener bug all over again — Caddy is inside a container whose
	// ports compose maps. Without one it matches the Host header on whatever port it is serving,
	// so `box.local` correctly answers a request whose Host is `box.local:8443`.
	host = stripHostPort(host)

	var b strings.Builder
	b.WriteString("# Generated by `ptln server install`. Edit freely — a re-install does not\n")
	b.WriteString("# overwrite a Caddyfile you have changed.\n\n")

	// DO NOT set http_port / https_port here.
	//
	// They change the ports Caddy LISTENS on, and Caddy is inside a container whose ports are
	// mapped by compose as `${HTTP_PORT}:80` and `${HTTPS_PORT}:443` — the container side is
	// fixed. Setting them to the host ports made Caddy listen on 8880/8443 inside the container
	// while compose forwarded to 80/443, where nothing was listening: the certificate was issued
	// correctly and every request still timed out. Leaving them unset keeps Caddy on 80/443,
	// which is exactly what the mapping expects.
	//
	// The cost is that Caddy's HTTP→HTTPS redirect names the default port, so on a remapped box
	// the redirect points at :443 rather than :8443. Hitting HTTPS directly works, which is what
	// the installer verifies and what the report tells the operator to use.
	var global []string
	if mode == tlsOff {
		global = append(global, "auto_https off")
	}
	if tunnelFronted(cfg) {
		// THE LINE A TUNNEL NEEDS. Caddy overwrites X-Forwarded-Proto with its own view of the
		// request — http, since the tunnel hands us plain HTTP — unless the proxy in front is
		// trusted. Keycloak reads that header (KC_PROXY_HEADERS=xforwarded) and its realm
		// demands https, so without this line every sign-in behind a tunnel is refused as
		// insecure while the browser shows a padlock. The tunnel connects from this machine or
		// the compose network, so private_ranges is the right scope.
		global = append(global, "servers {\n\t\ttrusted_proxies static private_ranges\n\t}")
	}
	if isIPHost(host) && mode != tlsOff {
		// A client connecting to an IP ADDRESS sends no SNI — TLS server-name indication
		// carries a name, and there isn't one. Without a default, Caddy has no way to pick a
		// certificate and the handshake simply fails: HTTP redirects fine, HTTPS answers
		// nothing. default_sni tells it which site to serve when the client names none.
		global = append(global, "default_sni "+host)
	}
	if len(global) > 0 {
		b.WriteString("{\n")
		for _, g := range global {
			fmt.Fprintf(&b, "\t%s\n", g)
		}
		b.WriteString("}\n\n")
	}

	addr := host
	if mode == tlsOff {
		addr = "http://" + host
	}
	fmt.Fprintf(&b, "%s {\n", addr)
	switch mode {
	case tlsInternal:
		b.WriteString("\t# No public domain, so no public CA can issue. Caddy mints a certificate\n")
		b.WriteString("\t# from its own local CA: HTTPS works now, offline, with a browser warning\n")
		b.WriteString("\t# until you trust that CA. Swap this for a real name to get rid of it.\n")
		b.WriteString("\ttls internal\n\n")
	case tlsACME:
		b.WriteString("\t# A public name, so Caddy asks Let's Encrypt for a real certificate on\n")
		b.WriteString("\t# first request. That needs this box reachable from the internet.\n\n")
	case tlsOff:
		b.WriteString("\t# Plain HTTP by request (--tls off). Nothing is encrypted in transit.\n\n")
	}
	b.WriteString(caddyRoutes())
	b.WriteString("}\n\n")

	// The INTERNAL door, on the container network.
	//
	// The web container reaches PostgREST through Caddy, because the path prefix matters:
	// supabase-js appends /rest/v1/ and `handle_path` strips it before proxying. So the app
	// cannot simply be pointed at postgrest:3000 — it would arrive with the prefix still on and
	// get a 404.
	//
	// It cannot use the PUBLIC url either. That is what shipped, and on a self-hosted box it
	// fails: PGRST_URL was the site URL, so a container asking for https://127.0.0.1 asked
	// ITSELF, and every server-side query died with "fetch failed" — sign-in included. Even with
	// a real hostname it needs the container to resolve the public name and hairpin back in,
	// which frequently does not work on a private network.
	//
	// A plain-HTTP block matched on the compose SERVICE NAME solves both: no DNS, no TLS, no
	// trip outside the box. It answers only to Host: caddy, which nothing off the container
	// network sends, and serves exactly the same routes as the public block regardless.
	b.WriteString("# Internal, on the container network only (Host: caddy). The app uses this to\n")
	b.WriteString("# reach PostgREST without leaving the box — see PGRST_URL in .env.\n")
	b.WriteString("http://caddy {\n")
	b.WriteString(caddyRoutes())
	b.WriteString("}\n")
	return b.String()
}

// caddyRoutes is the routing shared by the public and internal site blocks. One definition, so the
// two doors can never drift into serving different things.
func caddyRoutes() string {
	var b strings.Builder
	b.WriteString("\thandle_path /rest/v1/* {\n\t\treverse_proxy postgrest:3000\n\t}\n\n")
	// THE BUNDLED IDENTITY PROVIDER, WITHOUT WHICH NOBODY CAN SIGN IN.
	//
	// This route was missing, and its absence is invisible until the first sign-in: /auth/* fell
	// through to the catch-all below and reached the Next.js app, which has no such route. So
	// OIDC discovery — the web container fetching ${OIDC_ISSUER}/.well-known/openid-configuration,
	// and OIDC_ISSUER is SITE_URL/auth/realms/partyline — got the app's 404 instead of Keycloak's
	// document, and every login died. Caddyfile.staging has always carried this block; the
	// generated one did not.
	//
	// `handle`, NOT `handle_path`: Keycloak runs with KC_HTTP_RELATIVE_PATH=/auth and publishes
	// issuer URLs that contain /auth, so stripping the prefix makes every published URL 404.
	b.WriteString("\thandle /auth/* {\n\t\treverse_proxy keycloak:8080\n\t}\n\n")
	b.WriteString("\thandle {\n\t\treverse_proxy web:3000 {\n")
	b.WriteString("\t\t\t# Ride out a container swap rather than 502ing during a deploy.\n")
	b.WriteString("\t\t\tlb_try_duration 30s\n\t\t\tlb_try_interval 250ms\n\t\t\tfail_duration 0\n")
	b.WriteString("\t\t}\n\t}\n")
	return b.String()
}

// internalPgrstURL is what the app should use for PostgREST: the internal Caddy door above.
const internalPgrstURL = "http://caddy"

// tlsModeNote is the one line the plan prints about certificates, so the operator knows what they
// are getting BEFORE the install rather than discovering it in a browser.
func tlsModeNote(cfg installConfig) string {
	switch resolveTLSMode(cfg.tls, cfg.site) {
	case tlsACME:
		return "a real certificate from Let's Encrypt (this box must be reachable from the internet on the public 80/443)"
	case tlsInternal:
		return "a self-signed certificate from Caddy's own CA — no public domain needed, but browsers will warn until you trust it"
	case tlsOff:
		return "none — plain HTTP, nothing encrypted in transit"
	}
	return ""
}
