package main

// PROTOTYPE — tmux-backed session host (`ptln tmux`).
//
// This is Option 3 from the mux-corruption analysis: instead of the built-in pass-through
// multiplexer (internal/ptymux) owning the terminal, tmux does. tmux keeps a full server-side
// grid per window, so switching between differential-redraw TUIs (claude, codex) can never
// leave stale cells behind — the exact structural defect the pass-through mux cannot fix.
//
// Scope of the prototype:
//   - `ptln tmux`           one window running the quick engine (PARTYLINE_ENGINE or claude)
//   - `ptln tmux --resume`  one window per saved workspace session (same resume argv the
//     built-in mux would use, permission flags included)
//   - branded status bar (wordmark amber, focused-tab pill pink), ctrl-\ prefix to match
//     the built-in mux's chord, n/N new-session keys mirroring the switchboard
//
// NOT in the prototype (deliberately): the launcher/home screen, session sharing, thread
// wiring, boot splash, workspace save-on-quit. Those come if the backend graduates.
//
// Everything runs on a private tmux server (socket "partyline") so the user's own tmux
// sessions are untouched.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"partyline.sh/partyline/internal/brand"
	"partyline.sh/partyline/internal/ptymux"
)

// tmuxWindow is one window in the plan: a name, a working dir, and the argv tmux execs
// directly (no shell — argv words are passed as separate arguments, so no quoting games).
type tmuxWindow struct {
	name string
	dir  string
	argv []string
}

// tmuxLaunch is the full, inspectable plan: the generated conf and the windows to open.
// Building it is pure; only runTmux touches the world.
type tmuxLaunch struct {
	socket  string
	conf    string
	windows []tmuxWindow
}

const tmuxSocket = "partyline"
const tmuxSessionName = "ptln"

func tmuxCmdMain(args []string) {
	resume := false
	printConf := false
	for _, a := range args {
		switch a {
		case "--resume":
			resume = true
		case "--print-conf":
			printConf = true
		default:
			fatal(fmt.Errorf("ptln tmux: unknown flag %q", a))
		}
	}

	cwd, _ := os.Getwd()
	var specs []ptymux.Spec
	if resume {
		specs = dropHeldForks(loadWorkspace())
		if len(specs) == 0 {
			fmt.Println("no saved workspace — starting a fresh session instead")
		}
	}
	plan := buildTmuxLaunch(cwd, specs)

	if printConf {
		fmt.Print(plan.conf)
		return
	}

	if os.Getenv("TMUX") != "" {
		fatal(fmt.Errorf("ptln tmux: already inside a tmux session — detach first (prefix d)"))
	}
	if _, err := exec.LookPath("tmux"); err != nil {
		fatal(fmt.Errorf("ptln tmux: tmux is not installed (brew install tmux / apt install tmux)"))
	}

	if err := runTmux(plan); err != nil {
		fatal(fmt.Errorf("ptln tmux: %w", err))
	}
}

// buildTmuxLaunch turns the workspace (or a fresh quick session) into a launch plan.
// Pure: no filesystem, no processes.
func buildTmuxLaunch(cwd string, specs []ptymux.Spec) tmuxLaunch {
	var wins []tmuxWindow
	for _, s := range specs {
		if len(s.Argv) == 0 {
			continue
		}
		dir := s.Dir
		if dir == "" {
			dir = cwd
		}
		wins = append(wins, tmuxWindow{name: tmuxWindowName(s.Label), dir: dir, argv: s.Argv})
	}
	if len(wins) == 0 {
		engine := quickNewEngine()
		wins = []tmuxWindow{{name: tmuxWindowName(engine + " · " + filepath.Base(cwd)), dir: cwd, argv: []string{engine}}}
	}
	return tmuxLaunch{socket: tmuxSocket, conf: tmuxConf(), windows: wins}
}

// tmuxWindowName keeps labels safe for the status bar: control chars stripped, length capped.
var tmuxUnprintable = regexp.MustCompile(`[[:cntrl:]#]`)

func tmuxWindowName(label string) string {
	s := tmuxUnprintable.ReplaceAllString(label, "")
	s = strings.TrimSpace(s)
	if s == "" {
		s = "session"
	}
	if len([]rune(s)) > 24 {
		s = string([]rune(s)[:24])
	}
	return s
}

// tmuxConf renders the generated config. Brand colors come from the brand package
// (wordmark amber, focused-pill pink) so a palette change there reaches this bar too.
func tmuxConf() string {
	amber := brand.Hex(brand.AmberRGB)
	pill := brand.Hex(brand.PillRGB)
	engine := quickNewEngine()
	quick := shQuote(engine)
	bypassWords := append([]string{engine}, bypassFlagsFor(engine)...)
	quoted := make([]string, len(bypassWords))
	for i, w := range bypassWords {
		quoted[i] = shQuote(w)
	}
	bypass := strings.Join(quoted, " ")

	var b strings.Builder
	w := func(line string) { b.WriteString(line + "\n") }

	w(`# GENERATED by ptln tmux (prototype backend). Rewritten on every launch — do not edit.`)
	w(``)
	w(`set -g default-terminal "tmux-256color"`)
	w(`set -ga terminal-overrides ",*:RGB"`)
	w(`set -s escape-time 0`)
	w(`set -g history-limit 50000`)
	w(`set -g mouse on`)
	w(`set -g base-index 1`)
	w(`setw -g pane-base-index 1`)
	w(`set -g renumber-windows on`)
	w(`setw -g aggressive-resize on`)
	w(`set -g set-titles on`)
	w(`set -g set-titles-string "ptln · #W"`)
	w(``)
	w(`# ---- prefix: ctrl-\ (the same chord the built-in mux answers to) ----`)
	w(`unbind C-b`)
	w(`set -g prefix 'C-\'`)
	w(`bind 'C-\' send-prefix`)
	w(``)
	w(`# ---- partyline chords (prefix first, then the key) ----`)
	w(`bind n new-window -c "#{pane_current_path}" ` + quick)
	w(`bind N new-window -c "#{pane_current_path}" "` + strings.ReplaceAll(bypass, `"`, `\"`) + `"`)
	w(`bind t new-window -c "#{pane_current_path}"`)
	w(`bind o choose-tree -Zw`)
	w(`bind q detach`)
	w(`bind x confirm-before -p "close this window? (y/n)" kill-window`)
	w(`bind '|' split-window -h -c "#{pane_current_path}"`)
	w(`bind - split-window -v -c "#{pane_current_path}"`)
	for i := 1; i <= 9; i++ {
		w(fmt.Sprintf(`bind -n M-%d select-window -t %d`, i, i))
	}
	w(``)
	w(`# ---- status bar (partyline brand) ----`)
	w(`set -g status on`)
	w(`set -g status-position bottom`)
	w(`set -g status-interval 5`)
	w(`set -g status-style "bg=#101010,fg=#8a8a8a"`)
	w(`set -g status-left "#[fg=` + amber + `,bold] ☎ PARTYLINE #[default]"`)
	w(`set -g status-left-length 24`)
	w(`set -g status-right "#[fg=#8a8a8a]%H:%M #[fg=` + amber + `][tmux proto]#[default] "`)
	w(`set -g status-right-length 40`)
	w(`setw -g window-status-separator ""`)
	w(`setw -g window-status-format "#[fg=#8a8a8a] #I·#W "`)
	w(`setw -g window-status-current-format "#[bg=` + pill + `,fg=#101010,bold] #I·#W #[default]"`)
	w(`setw -g window-status-activity-style "fg=` + amber + `"`)
	w(`set -g message-style "bg=#101010,fg=` + amber + `"`)
	w(`set -g mode-style "bg=` + amber + `,fg=#101010"`)
	w(`set -g pane-border-style "fg=#3a3a3a"`)
	w(`set -g pane-active-border-style "fg=` + amber + `"`)
	return b.String()
}

// runTmux writes the conf, builds the session if it isn't already running, and attaches.
// An existing "ptln" session on the private socket is attached as-is — the plan's windows
// only apply on a fresh server, so a detach/reattach never duplicates sessions.
func runTmux(plan tmuxLaunch) error {
	confPath := filepath.Join(stateDir(), "tmux.conf")
	if err := os.MkdirAll(stateDir(), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(confPath, []byte(plan.conf), 0o644); err != nil {
		return err
	}

	base := []string{"-L", plan.socket, "-f", confPath}
	tm := func(args ...string) *exec.Cmd { return exec.Command("tmux", append(base, args...)...) }

	if tm("has-session", "-t", tmuxSessionName).Run() != nil {
		// Fresh server: create detached with window 1, add the rest, then attach.
		first := plan.windows[0]
		newArgs := []string{"new-session", "-d", "-s", tmuxSessionName, "-n", first.name, "-c", first.dir, "--"}
		newArgs = append(newArgs, first.argv...)
		if out, err := tm(newArgs...).CombinedOutput(); err != nil {
			return fmt.Errorf("new-session: %v\n%s", err, out)
		}
		for _, win := range plan.windows[1:] {
			winArgs := []string{"new-window", "-t", tmuxSessionName, "-d", "-n", win.name, "-c", win.dir, "--"}
			winArgs = append(winArgs, win.argv...)
			if out, err := tm(winArgs...).CombinedOutput(); err != nil {
				fmt.Fprintf(os.Stderr, "ptln tmux: could not open %q: %v\n%s", win.name, err, out)
			}
		}
		_ = tm("select-window", "-t", tmuxSessionName+":1").Run()
	} else {
		fmt.Println("☎ existing partyline tmux session — attaching (prefix is ctrl-\\, `q` detaches)")
	}

	attach := tm("attach-session", "-t", tmuxSessionName)
	attach.Stdin, attach.Stdout, attach.Stderr = os.Stdin, os.Stdout, os.Stderr
	return attach.Run()
}
