package features

import "sort"

// Every environment variable the code reads must be EITHER declared in features.json as gating a
// feature, or classified here with the reason it is not one. That closing rule is what makes the
// registry stay true: a new `process.env.NEW_THING` that gates a feature cannot be added without
// someone either declaring it or writing down why it is not a gate. It is the same shape as
// docsaudit.RequiresDoc — an exemption you have to state out loud, not an omission you can drift
// into. drift.go enforces both directions.
//
// This table is also where the non-feature half of deploy/stack/env.example comes from, so the
// generated file still tells an operator how to bring a box up, not just which features exist.

// Class says why a variable is not a feature gate.
type Class string

const (
	// Core: the server does not run correctly without it. Not a feature — there is no state in
	// which the app is up and this is legitimately unset.
	Core Class = "core"
	// Compose: read by docker compose or the init scripts, never by application code. Belongs in
	// the box's .env but can never appear in the extractor's output.
	Compose Class = "compose"
	// Optional: tunes or provides a fallback for something already declared. Unset is a supported
	// state with a documented default, so it is not part of any feature's configured/not answer.
	Optional Class = "optional"
	// Client: read by the CLI on a user's own machine. Not server configuration at all, and must
	// never appear in the deploy env example.
	Client Class = "client"
)

// NonFeature is one classified variable. Why is prose for a human; Example is the line the
// generated env.example carries (empty means "no default — fill it in").
type NonFeature struct {
	Name    string
	Class   Class
	Why     string
	Example string
}

// NonFeatures is the classification table. Keep it alphabetical within each class.
var NonFeatures = []NonFeature{
	// ---- core: the app is broken without these ----
	{Name: "NEXT_PUBLIC_PARTYLINE_ENV", Class: Core, Why: "which environment the browser bundle reports to Sentry/PostHog", Example: "staging"},
	{Name: "NEXT_PUBLIC_SITE_URL", Class: Core, Why: "the site origin the browser bundle links to", Example: "https://staging.partyline.sh"},
	{Name: "NEXT_PUBLIC_SUPABASE_ANON_KEY", Class: Core, Why: "the anon PostgREST key; baked into the web image at BUILD time on the CI runner, not set here"},
	{Name: "NEXT_PUBLIC_SUPABASE_URL", Class: Core, Why: "the PostgREST origin the browser bundle uses; baked in at BUILD time, not set here"},
	{Name: "NEXT_RUNTIME", Class: Core, Why: "set by Next itself to pick the server vs edge Sentry config"},
	{Name: "NODE_ENV", Class: Core, Why: "set by Next itself; production/development"},
	{Name: "PGRST_ANON_KEY", Class: Core, Why: "the anon JWT the server-side PostgREST client presents"},
	{Name: "PGRST_URL", Class: Core, Why: "PostgREST's origin, read at RUNTIME so one image can serve both boxes", Example: "http://postgrest:3000"},
	{Name: "SESSION_JWT_SECRET", Class: Core, Why: "signs our session JWTs; must be byte-identical to PGRST_JWT_SECRET and TRIMMED — a trailing newline mints tokens PostgREST silently rejects"},
	{Name: "SITE_URL", Class: Core, Why: "the canonical origin every server-rendered link and email is built from", Example: "https://staging.partyline.sh"},
	{Name: "SUPABASE_SERVICE_ROLE_KEY", Class: Core, Why: "the admin bypass every adminClient() call uses — treat as root"},

	// ---- compose: read by the stack, never by application code ----
	{Name: "AUTHENTICATOR_PASSWORD", Class: Compose, Why: "PostgREST's login role; must match the bootstrap in deploy/stack/init/"},
	{Name: "MINIO_REPLICAS", Class: Compose, Why: "set 0 to stop running the bundled MinIO on a box that points S3_* at R2 or S3; unset = 1", Example: "1"},
	{Name: "MINIO_ROOT_PASSWORD", Class: Compose, Why: "the bundled MinIO's root password, generated by scripts/env-bootstrap.sh — never a default"},
	{Name: "MINIO_ROOT_USER", Class: Compose, Why: "the bundled MinIO's root user, generated by scripts/env-bootstrap.sh", Example: "partyline"},
	{Name: "POSTGRES_PASSWORD", Class: Compose, Why: "the database superuser password (openssl rand -base64 32)"},
	{Name: "RELAY_IMAGE", Class: Compose, Why: "overrides the WHOLE relay image reference; the only way to pin a digest, since @ is illegal in a tag. Unset = whatever RELAY_TAG names"},
	{Name: "RELAY_TAG", Class: Compose, Why: "the relay image tag compose runs; upserted by the deploy workflow alongside WEB_TAG", Example: "latest"},
	{Name: "WEB_IMAGE", Class: Compose, Why: "overrides the WHOLE web image reference, e.g. ghcr.io/partyline-sh/partyline-web@sha256:… or your own mirror. Unset = whatever WEB_TAG names", Example: ""},
	{Name: "WEB_TAG", Class: Compose, Why: "the image tag compose runs; upserted by the deploy workflow, set by hand to pin or roll back. The images are public — see deploy/stack/README.md for pinning", Example: "latest"},

	// ---- optional: a supported unset state with a documented default ----
	// Selects the sign-in adapter behind the auth seam (H.3a). OPTIONAL rather than Core because an
	// unset value is not a broken box: it means WorkOS, which is what partyline.sh runs and must keep
	// running. Only a self-hosted instance sets this, and only to name a different provider.
	{Name: "AUTH_PROVIDER", Class: Optional, Why: "which sign-in adapter to use; unset = workos, which is what partyline.sh runs", Example: "oidc"},
	{Name: "PARTYLINE_CLI_NOTICE", Class: Optional, Why: "one-line notice shown to CLIs on their update check; empty = none"},
	{Name: "PARTYLINE_MIN_CLI", Class: Optional, Why: "minimum supported CLI version; unset = 0.0.0, nothing is gated"},
	{Name: "PARTYLINE_RELEASE", Class: Optional, Why: "release tag attached to Sentry events; unset = untagged"},
	{Name: "PARTYLINE_SCRIBE_MODEL", Class: Optional, Why: "overrides the scribe's default model"},
	{Name: "PARTYLINE_SCRIBE_PROVIDER", Class: Optional, Why: "overrides the scribe's default provider (anthropic)"},
	{Name: "POSTHOG_HOST", Class: Optional, Why: "PostHog region; unset = US cloud. Set https://eu.i.posthog.com for EU"},
	{Name: "R2_ACCESS_KEY_ID", Class: Optional, Why: "legacy name still honoured as a fallback for S3_ACCESS_KEY_ID; do not set on a new box"},
	{Name: "R2_BUCKET", Class: Optional, Why: "legacy name still honoured as a fallback for S3_BUCKET; do not set on a new box"},
	{Name: "R2_ENDPOINT", Class: Optional, Why: "legacy name still honoured as a fallback for S3_ENDPOINT; do not set on a new box"},
	{Name: "R2_SECRET_ACCESS_KEY", Class: Optional, Why: "legacy name still honoured as a fallback for S3_SECRET_ACCESS_KEY; do not set on a new box"},
	{Name: "S3_FORCE_PATH_STYLE", Class: Optional, Why: "overrides object-storage addressing; unset = path style for a bare host (MinIO), virtual-hosted otherwise"},
	{Name: "S3_REGION", Class: Optional, Why: "object-storage region; unset = auto, which R2 and MinIO accept. Real AWS S3 needs the bucket's region"},
	{Name: "SLACK_STATE_SECRET", Class: Optional, Why: "signs the Slack OAuth CSRF state; falls back to SESSION_JWT_SECRET, which is the #175 footgun — set it to finish the split"},
	{Name: "SUPABASE_JWT_SECRET", Class: Optional, Why: "legacy name still honoured as a fallback for SLACK_STATE_SECRET; do not set on a new box"},
	{Name: "WORKOS_REDIRECT_URI", Class: Optional, Why: "OAuth callback; falls back to SITE_URL + /api/auth/callback", Example: "https://staging.partyline.sh/api/auth/callback"},

	// ---- client: the CLI on a user's machine, never server configuration ----
	{Name: "ALACRITTY_SOCKET", Class: Client, Why: "terminal detection for opening a session in a new window"},
	{Name: "ALACRITTY_WINDOW_ID", Class: Client, Why: "terminal detection"},
	{Name: "CI", Class: Client, Why: "suppresses the telemetry notice and the update check in CI"},
	{Name: "CLAUDE_CODE_SESSION_ID", Class: Client, Why: "set by claude; identifies the session an agent is speaking from"},
	{Name: "COLORTERM", Class: Client, Why: "truecolor detection for the wordmark"},
	{Name: "DO_NOT_TRACK", Class: Client, Why: "the standard telemetry opt-out, honoured by the CLI"},
	{Name: "EDITOR", Class: Client, Why: "the editor ctrl-e opens for a long message"},
	{Name: "GNOME_TERMINAL_SCREEN", Class: Client, Why: "terminal detection"},
	{Name: "KITTY_WINDOW_ID", Class: Client, Why: "terminal detection"},
	{Name: "KONSOLE_VERSION", Class: Client, Why: "terminal detection"},
	{Name: "NO_COLOR", Class: Client, Why: "the standard colour opt-out"},
	{Name: "NO_UPDATE_NOTIFIER", Class: Client, Why: "the conventional opt-out for update nagging"},
	{Name: "PAGER", Class: Client, Why: "pager for `ptln man` and long TUI output"},
	{Name: "PARTYLINE", Class: Client, Why: "marker exported into a shared shell so a nested ptln knows it is inside one"},
	{Name: "PARTYLINE_AGENT_NAME", Class: Client, Why: "the name an MCP-wired agent reports itself as"},
	{Name: "PARTYLINE_ALLOW_TEMP_CONNECT", Class: Client, Why: "dev escape hatch for connecting a thread without an account"},
	{Name: "PARTYLINE_API", Class: Client, Why: "points the CLI at a different control plane (local dev, staging)"},
	{Name: "PARTYLINE_CHECKUP_IDLE_SECS", Class: Client, Why: "mux idle-checkup tuning"},
	{Name: "PARTYLINE_CHECKUP_POLL_SECS", Class: Client, Why: "mux idle-checkup tuning"},
	{Name: "PARTYLINE_CRANK_WORKERS", Class: Client, Why: "default worker count for crank/daemon on this machine"},
	{Name: "PARTYLINE_DAEMON_TOKEN", Class: Client, Why: "the daemon's own token, handed to workers it spawns"},
	{Name: "PARTYLINE_ENGINE", Class: Client, Why: "which engine an MCP-wired session is running"},
	{Name: "PARTYLINE_MAX_TOKENS", Class: Client, Why: "token ceiling for a crank run"},
	{Name: "PARTYLINE_MCP_EXPERIMENTAL", Class: Client, Why: "opts a party runner into experimental MCP wiring"},
	{Name: "PARTYLINE_NAME", Class: Client, Why: "display name for this machine's sessions"},
	{Name: "PARTYLINE_NO_CONNECT_PROMPT", Class: Client, Why: "suppresses the first-run MCP connect prompt"},
	{Name: "PARTYLINE_NO_MCP", Class: Client, Why: "runs a party agent with no MCP servers at all"},
	{Name: "PARTYLINE_NO_UPDATE_CHECK", Class: Client, Why: "suppresses the CLI update check"},
	{Name: "PARTYLINE_PARTY_ID", Class: Client, Why: "the party an MCP-wired agent belongs to"},
	{Name: "PARTYLINE_PARTY_TOKEN", Class: Client, Why: "that agent's party token"},
	{Name: "PARTYLINE_RELAY", Class: Client, Why: "points the CLI at a different relay host"},
	{Name: "PARTYLINE_RUN_ID", Class: Client, Why: "the control-plane run a worker is reporting to"},
	{Name: "PARTYLINE_SESSION_KEY", Class: Client, Why: "the session key an MCP-wired agent authenticates with"},
	{Name: "PARTYLINE_SESSION_LABEL", Class: Client, Why: "the label ask_session publishes this session under"},
	{Name: "PARTYLINE_TELEMETRY", Class: Client, Why: "0 opts this machine out of CLI telemetry"},
	{Name: "PARTYLINE_THREAD_ID", Class: Client, Why: "the context thread a session is attached to"},
	{Name: "PARTYLINE_VISUAL", Class: Client, Why: "visual preset for crank output"},
	{Name: "PATH", Class: Client, Why: "inherited when installing the daemon/tray as a service"},
	{Name: "PTLN_BIN", Class: Client, Why: "the ptln binary the tray shells out to"},
	{Name: "PTLN_DEBUG", Class: Client, Why: "session-engine debug logging"},
	{Name: "PTLN_MUX_DEBUG", Class: Client, Why: "mux debug logging"},
	{Name: "PTLN_POWERLINE", Class: Client, Why: "powerline glyphs in the mux status bar"},
	{Name: "SHELL", Class: Client, Why: "the shell a shared session hosts"},
	{Name: "TERM_PROGRAM", Class: Client, Why: "terminal detection"},
	{Name: "TMUX", Class: Client, Why: "terminal detection"},
	{Name: "USER", Class: Client, Why: "fallback display name"},
	{Name: "WEZTERM_PANE", Class: Client, Why: "terminal detection"},
}

// Classify returns the classification for a variable, if it has one.
func Classify(name string) (NonFeature, bool) { return classifyIn(NonFeatures, name) }

func classifyIn(table []NonFeature, name string) (NonFeature, bool) {
	for _, n := range table {
		if n.Name == name {
			return n, true
		}
	}
	return NonFeature{}, false
}

// OfClass returns every classified variable in one class, sorted by name.
func OfClass(c Class) []NonFeature {
	var out []NonFeature
	for _, n := range NonFeatures {
		if n.Class == c {
			out = append(out, n)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}
